# .github/workflows/cypress-tests.yml
name: Cypress Tests CI

on:
  push:
    branches: [main, exercicios/modulo-4]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and Record on Dashboard

        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --record --group UI-Tests --tag ${{ github.ref_name }}
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
